@echo off
chcp 65001 >nul 2>&1
:: heredoc.bat - Here Document模拟演示
:: 安全提示：所有文件操作在脚本目录内进行，使用临时文件后自动清理

setlocal

:: 设置输出文件路径
set "OUT=%~dp0heredoc.txt"
set "HTML=%~dp0heredoc.html"
set "CONFIG=%~dp0heredoc.conf"

echo ========================================
echo Here Document模拟演示
echo ========================================
echo.
echo 注意：CMD没有真正的Here Document语法
echo 我们使用括号代码块模拟类似功能
echo.

echo === 1. 基本括号代码块 ===
echo 创建简单文本文件...
(
echo First line
echo Second line
echo Third line
) > "%OUT%"
echo 创建完成，文件内容：
type "%OUT%"
echo.

echo === 2. 生成HTML文件 ===
echo 创建HTML文件...
(
echo ^<!DOCTYPE html^>
echo ^<html lang="en"^>
echo ^<head^>
echo     ^<meta charset="UTF-8"^>
echo     ^<title^>Test Page^</title^>
echo     ^<style^>
echo         body { font-family: Arial, sans-serif; }
echo         h1 { color: #333; }
echo     ^</style^>
echo ^</head^>
echo ^<body^>
echo     ^<h1^>Hello from CMD!^</h1^>
echo     ^<p^>This HTML was generated using a batch script.^</p^>
echo     ^<ul^>
echo         ^<li^>Item 1^</li^>
echo         ^<li^>Item 2^</li^>
echo         ^<li^>Item 3^</li^>
echo     ^</ul^>
echo ^</body^>
echo ^</html^>
) > "%HTML%"
echo HTML文件创建完成，内容：
type "%HTML%"
echo.

echo === 3. 生成配置文件 ===
echo 创建配置文件...
(
echo # Application Configuration
echo # Generated by CMD script
echo.
echo [database]
echo host=localhost
echo port=3306
echo user=admin
echo password=secret123
echo.
echo [server]
echo address=0.0.0.0
echo port=8080
echo max_connections=100
echo.
echo [logging]
echo level=INFO
echo file=app.log
echo max_size=10MB
) > "%CONFIG%"
echo 配置文件创建完成，内容：
type "%CONFIG%"
echo.

echo === 4. 使用变量的括号代码块 ===
echo 创建包含变量的文件...
set "app_name=MyApp"
set "version=1.0.0"
set "author=CMD Developer"

(
echo Application: %app_name%
echo Version: %version%
echo Author: %author%
echo Date: %date%
echo Time: %time%
) > "%OUT%"
echo 变量替换后的文件内容：
type "%OUT%"
echo.

echo === 5. 追加到括号代码块 ===
echo 追加内容到文件...
(
echo.
echo # Additional settings
echo debug=true
echo verbose=false
) >> "%CONFIG%"
echo 追加后的配置文件内容：
type "%CONFIG%"
echo.

echo === 6. 嵌套括号的注意事项 ===
echo 注意：嵌套括号需要转义内层括号
echo 创建包含嵌套括号的内容...
(
echo if ^(condition^) ^(
echo     echo This works
echo ^)
) > "%OUT%"
echo 嵌套括号示例内容：
type "%OUT%"
echo.

echo === 7. 使用临时文件模拟复杂Here Doc ===
echo 创建复杂的多行内容...
set "TMPFILE=%TEMP%\heredoc_%RANDOM%.txt"

echo Creating complex content...
(
echo #!/bin/bash
echo # This is a shell script example
echo.
echo function greet^(^) ^{
echo     local name=$1
echo     echo "Hello, $name!"
echo     return 0
echo ^}
echo.
echo # Main execution
echo if [ "$#" -eq 0 ]; then
echo     greet "World"
echo else
echo     greet "$1"
echo fi
) > "%TMPFILE%"

echo 复杂内容创建完成，文件内容：
type "%TMPFILE%"
echo.

:: 清理临时文件
echo ========================================
echo 清理临时文件...
del "%OUT%" 2>nul
del "%HTML%" 2>nul
del "%CONFIG%" 2>nul
del "%TMPFILE%" 2>nul
echo 清理完成
echo ========================================

endlocal